name: Release Actions

on:
  release:
    types:
      - published

jobs:
  attach_usercss:
    name: Attach user-css file
    runs-on: "ubuntu-18.04"
    env:
      usercss_path: "./python_docs_*.user.css"

    steps:
      - uses: actions/checkout@v2

      - name: upload file
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "${{ env.usercss_path }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
